server:
  port: 8080

spring:
  application:
    name: amazon
  datasource:
    url: jdbc:postgresql://localhost:5432/wsd
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update